### ISSUE TITLE
ポートが使われていたorアクセス拒否の場合の再試行処理に回数制限をつけるべきかもしれない

### ISSUE THREAD

**Issue by typeling1578** [Floorp-Projects/User-Agent_Scraper#2]
全ポートがアクセス拒否される場合などに無限ループが発生してしまう。

**Comment by creeper-0910** [comment]
Node.jsで空きポートを調べる実装ができるようなので空きポートをチェックしてなければエラー落ちでもいいかも知れない

**Comment by typeling1578** [comment]
今現在の仕様としては、32768〜60999までの間でランダム選び、使われているか確認し、使われていなければそれを使う、使われていればもう一度ランダムに選んで確認する。
